
CREATE TABLE USER_TBL(
    USER_ID VARCHAR(60),
    USER_PASSWORD VARCHAR(60),
	SEX VARCHAR(60),
    AGE INT,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE SEARCH_CAR(
	USER_ID VARCHAR(60),
    CAR_NAME VARCHAR(60),
    DATE TIMESTAMP,
    CONSTRAINT FK_1 FOREIGN KEY (USER_ID) REFERENCES USER_TBL(USER_ID),
    CONSTRAINT FK_2 FOREIGN KEY (CAR_NAME) REFERENCES CARINFO_TBL(CAR_NAME),
    PRIMARY KEY (USER_ID,CAR_NAME,DATE)
);

CREATE TABLE SEARCH_COMPANY(
	USER_ID VARCHAR(60),
    COMPANY_NAME VARCHAR(60),
    DATE TIMESTAMP,
    CONSTRAINT FK_1C FOREIGN KEY (USER_ID) REFERENCES USER_TBL(USER_ID),
    CONSTRAINT FK_2C FOREIGN KEY(COMPANY_NAME) REFERENCES COMPANY_TBL (COMPANY_NAME),
    PRIMARY KEY (USER_ID,COMPANY_NAME,DATE)
);