
CREATE TABLE KIND_OF_CAR_TBL(
	CORD VARCHAR(60),
    KIND_OF VARCHAR(60),
    #CONSTRAINT FK_KIND FOREIGN KEY (CAR_NAME) REFERENCES CARINFO_TBL(CAR_NAME),
    PRIMARY KEY(CORD)
);

INSERT INTO KIND_OF_CAR_TBL VALUES
    ('LI','LIGHT_CAR'),
	('CO','COMPACT_CAR'),
    ('MI','MIDSIZE_CAR'),
	('SUV','SUV_CAR'),
	('FU','FULL_SIZE_CAR'),
	('SP','SPORTS_CAR'),
	('TR','TRUCK_CAR');